### PR TITLE
LRQA-40476 Add ability to sort list of string

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-40476

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
Testing updates here:
https://github.com/michaelhashimoto/com-liferay-poshi-runner/pull/18

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/38

**Pull request closed without merging**
