### PR TITLE
LRQA-40441 Account for 'ignore' attributes in both definition and command elements

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-40441

cc-ing: @pyoo47

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/32

**Pull request closed without merging**
